### ISSUE TITLE
Add SoftDeletableListenerExtensionBundle

### ISSUE THREAD

**Issue by Radcho** [TIS2017/Nobelisti#108]
Nainstalovat podla https://github.com/E-vence/SoftDeleteableListenerExtensionBundle#install
Pre kazdy foreign entitu pridat `@Evence\onSoftDelete(type="CASCADE")` alebo ` @Evence\onSoftDelete(type="SET NULL")`

**Comment by ZoltanOnody** [comment]
Kde je nullable treba dat null inak cascade
