### ISSUE TITLE
vytvorit navrh

### ISSUE THREAD

**Issue by ZoltanOnody** [TIS2017/Nobelisti#11]
https://docs.google.com/document/d/1axUoEoJlmkwXlNKhEKbb2x0q7DHuoH2Ff8lmfs-2WlM/edit

**Comment by andrejjursa** [comment]
@TIS2017/aaaa pridal som vam do dokumentu komentare.

**Comment by ZoltanOnody** [comment]
Dakujeme, zmeny sa pokuksime co v najkratsom case zapracovat.

**Comment by ZoltanOnody** [comment]
Na emaily budeme pouzivat message queue ako sme sa dohodli. Vybral som https://www.rabbitmq.com/.

Nasledujuce odkazy by mali stacit na to co potrebujeme my.
https://www.rabbitmq.com/tutorials/tutorial-one-php.html
https://www.rabbitmq.com/tutorials/tutorial-two-php.html

**Comment by ZoltanOnody** [comment]
Databaza.

Okrem https://symfony.com/doc/current/doctrine.html budeme potrebovat aj https://github.com/Atlantic18/DoctrineExtensions

konkretne:
https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/softdeleteable.md
https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/timestampable.md
https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/references.md (pravdepodobne)

**Comment by andrejjursa** [comment]
Nezabudnite na:
https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html (nutne pouzit)

**Comment by ZoltanOnody** [comment]
jasne vdaka :-)

**Comment by ZoltanOnody** [comment]
Nasiel som 2 celkom zaujimave zdroje na PHP, mozno pomozu aj inym.

http://www.phptherightway.com/
http://phpsecurity.readthedocs.io/en/latest/index.html
