### ISSUE TITLE
prototyp

### ISSUE THREAD

**Issue by ZoltanOnody** [TIS2017/Nobelisti#12]

**Comment by Saamoot** [comment]
@ZoltanOnody @nitrajka 
Hello, ohladom zachovania vizualu stranky uniba, co sme sa stretli na chodbe. Plati to pre backend frontend(registracia na event) nebude nic zachovavat.

A pre istotu znova pisem wireframe moze byt html sablona a pouzit sa moze boostrap 3/4 a vyssie.

**Comment by ZoltanOnody** [comment]
Vdaka, pouzili sme bootstrap 4. 

Vizual este nieje prisposobeny dizajnu uniba.sk a treba ho brat viacmenej ako wireframe. Dizajn bude prisposobeny az v nasledujucej etape.
