### ISSUE TITLE
testovacie scenare

### ISSUE THREAD

**Issue by ZoltanOnody** [TIS2017/Nobelisti#14]
vsimol som si, ze sme ich este nedali na github a teda bezny clovek sa k nim nevie dostat. pridavam ich teda sem.

https://docs.google.com/document/d/1z4wE-FO899q4gOg5Dt_2EUdMOxnrVRxcSaX6nSjX4rQ/edit?usp=sharing

**Comment by andrejjursa** [comment]
@ZoltanOnody mame toto uz ako pdfko v gite? Ak nie, tak prosim dajte tento aj ostatne dokumenty do gitu a mergnite to s mastrom. Pripadne odstatne branche, ak by to sposobovalo problem, rebasnite.

**Comment by ZoltanOnody** [comment]
@Radcho to prida. vcera sme sa o tom rozpravali, musime tam este zmenit cislovania stran a tak. Do buduceho stretnutia to vsak spravene isto bude, vsak @Radcho
