### ISSUE TITLE
Poziadavky na finalny dizajn

### ISSUE THREAD

**Issue by ZoltanOnody** [TIS2017/Nobelisti#16]
Dostali sme niekolko poziadavok na finalny dizajn. Su to drobnosti ktore na wireframeoch nemusia byt, kedze wireframi maju sluzit iba ako *big picture*. Vsetky poziadavky ktore na wireframeoch nie su zmenene uvediem tu, aby sa na nic nezabudlo.

- [ ] "UNASSIGNE"/"DELETE" namiesto textu treba dat ikonu (napr. http://fontawesome.io/icon/trash/ ) (osobne navrhujem text + ikonu, alebo ikonu a onHover zobrazit text)
- [ ] "EDIT" namiesto textu treba dat ikonu (napr. http://fontawesome.io/icon/pencil/ )
- [ ] vsetky povinne fieldy maju byt oznacene hviezdickou (vraj cervenou). bolo by fajn ich dat ako `<span class="required-identifier">*</span>` aby sa popripade vedela zmenit farba na nieco krajsie)
- [ ] assign language/organizer modal - treba mat moznost vybrat naraz viacero organizatorov/jazykov. (idealne tych uz vybranych nejako zvyraznit)
- [ ] datetime picker
- [ ] unifikovat nazvy buttonov Save/Add/Edit
- [x] Zmazat zbytocne containers, Vyhodit z dockera
- [x] Upresnit navod pre pouzivatelov
- [x] Pridat requirements do README.md
- [x] Opravit permissions, Na co najmenej miestach root user, Co najmensie privliegia
- [x] Dorobit css styles, assign languages modal nezobrazoval jazyky (Linux/Firefox)

**Comment by ZoltanOnody** [comment]
@Saamoot mozme datetime picker vyriesit cez https://caniuse.com/#feat=input-datetime ? Je 2017 uz to podporuje kazdy rozumny prehliadac.

**Comment by Saamoot** [comment]
@ZoltanOnody 



date-time-picker
----
ak mas na mysli `<input type="date" .... />` resp. inym "nativnym" input typom, tak bohuzial odpoved je nie.

Dovody:
- slaba podpora IE(hlavne stare verzie robia problem kedze sa stale pomerne casto vyskytuju hlavne v pracovnych prostrediach),
- format datumu a casu je zavisli na formate casu a datumu OS pod ktorym sa stranka nacitala (napr u mna je to yyyy-mm-dd HH:mm ale kludne niekto moze mat mm. dd. yyy hh:mm tt) co je vizualne fajn na pracu s takymi udajmi nie,
- nekompletny date-time picker, datum som vedel pekne vybrat klikanim, no na vyber casu tam ziadne vyzualne prvky nie su (mozno som nieco robil zle ?).

fieldy maju byt oznacene hviezdickou (vraj cervenou)
---
cervena hviezdicka je nieco na co su ludia zvyknuti preto som to napisal na priamo, implementacne je riesenie pomocou triedy spravne

ikony - obrazky
----
kludne mozy byt pouzite tie, ak by sa boli "farebne" oznacene v podstate ako to ma boot strap na mazanie "danger"-like triedy a na upravu "warning"-like triedy 

ikony - text + ikonu
---
ten text znie fajn ale nie stale ho tam mat takze ako si spomenul `:hover` event je fajnt. Takze napr. `tooltip` z bootstrap-u ?

**Comment by ZoltanOnody** [comment]
ano, myslel som nativny input. 

- k pridavaniu eventov bude mat pristup iba admin. kto momentalne nahadzuje eventy? ty, peta, peto? Ak by toto malo sluzit pre beznych uzivatelov (attendees) bral by som to ako padny argument. Ano, mas pravdu IEcko toto nepodporuje, ale sprava sa to ako klasicky `type="text"` takze aj na starych prehliadacoch sa to bude dat nastavit. Nie tak komfortne, ale to je cena za to, ze clovek pouziva stare technologie.
- na datum sluzi `type="date"` na cas sluzi `type="time"`
- K formatu datu a casu https://stackoverflow.com/a/9519493/2317085

**Comment by andrejjursa** [comment]
@ZoltanOnody @Saamoot chapem, ze Zolo by rad vyuzil novy pristup vychadzajuci z najnovsich standardov HTML, ktore su obcas aj zadratovane v nejakych prehliadacoch, ked ale Tomas chce mat univerzalne funkcny datetime picker, tak ho pouzite, vsak ho [mozete mat priamo v Bootstrape](https://eonasdan.github.io/bootstrap-datetimepicker/) ([github](https://github.com/Eonasdan/bootstrap-datetimepicker)).

**Comment by ZoltanOnody** [comment]
[datepicker.zip](https://github.com/TIS2017/Nobelisti/files/1562808/datepicker.zip)

tu je datepicker ktory podporuje bootstrap4, tento pouzijme

**Comment by Saamoot** [comment]
Vzhladom je prijatelny, mne sa nepodarilo dosiahnut nejake nastavenie, ze by to bolo dobre na pouzitie. Skuste spravit nejake "config demo", ktore potom viete pozuit ale ja budem vidiet vysledok pred tym, nez to zadratujete do apliakcie a bude teda este prijatelne robit zmeny.

**Comment by andrejjursa** [comment]
hlavne to prosim importujte cez composer/npm a nie priamo davajte do repozitara, plati pre vsetky dependency co to podporuju

**Comment by ZoltanOnody** [comment]
@Saamoot ake konkretne nastavenia si mal na myslis? Mne sa zdalo, ze to splnalo vsetko co malo, no mozno som na nieco zabudol

@andrejjursa vo vseovecnosti OK. Pri tomto to vsak nepojde, tento datepicker som nasiel tu https://wireddots.com/products/datetimepicker

**Comment by Saamoot** [comment]
@ZoltanOnody spravanie pri vyberani casu a datumu, po vybrati dna sa neaktualizovala hodnota v input-e, to iste pri vybere casu. V deme na stranke mali tlacitko "apply" to sa mi nepodarilo pridat cez konfikuraciu plugin-u ked som to skusal lokalne. Aktualizacia input-u po event-e "blur" mi pride ako velmi zly sposob.
