### ISSUE TITLE
project structure

### ISSUE THREAD

**Issue by ZoltanOnody** [TIS2017/Nobelisti#2]
we need to create the project structure. we agreed that we will use docker.

**Comment by andrejjursa** [comment]
@ZoltanOnody Neviem, ci si na to uz prisiel, ale dev environment Symfony sa da spustit iba z localhost, takze treba patricne nakonfigurovat docker.

**Comment by ZoltanOnody** [comment]
todo:
- [ ] nahradit nginx za apache (tomas by bol rad) (https://github.com/convox-examples/httpd/blob/master/docker-compose.yml, https://hub.docker.com/_/httpd/)
- [ ] pridat xdebug (https://xdebug.org/)
- [ ] rabbitmq ( https://github.com/micahhausler/rabbitmq-compose/blob/master/docker-compose.yml, https://docs.docker.com/samples/library/rabbitmq/#rabbitmqversion)
