### ISSUE TITLE
Add crud for event_type

### ISSUE THREAD

**Issue by nitrajka** [TIS2017/Nobelisti#42]
- [x] entita event_type
- [x] list event_type in table
- [x] add
- [x] edit
- [x] delete (with modal)
Extends: #17

**Comment by ZoltanOnody** [comment]
pridat field ktory povie kolko hodin/dni pred uzatovrenim sa notifikacie poslu

**Comment by nitrajka** [comment]
To bolo v navrhu? Ved to patri k event-u. Kazdy event moze mat iny threshold

**Comment by ZoltanOnody** [comment]
Tak to tam presun

**Comment by ZoltanOnody** [comment]
Kedze tato issue ma blokuje v dalsej robote a nemyslim si, ze by si sa @nitrajka k tomu medzi sviatkami dostala, vezmem si to s nakodim to ak sa nenahnevas :-)

**Comment by ZoltanOnody** [comment]
Mozem os*at cele symfony. @nitrajka  necham to na teba. Ja skusim zistit preco ani hlupe `UniqueEntity` v tomto hlupom frameworku nefunguje.

**Comment by pavelpetrovic** [comment]
prosim zachovajte pokoj a dýchajte z hlboka!
tesim sa, ze projekt postupne tlacite vpred! aj ked to nie je priamociara cesta, ale to je normalne.

**Comment by andrejjursa** [comment]
> Mozem os*at cele symfony. @nitrajka  necham to na teba. Ja skusim zistit preco ani hlupe `UniqueEntity` v tomto hlupom frameworku nefunguje.

@ZoltanOnody co si sa snazil dosiahnut, ked ti to nefunguje?

**Comment by ZoltanOnody** [comment]
Snazil som sa zarucit aby `slug` + `deleted` boli spolu unique.

Medzicasom som vsak prisiel na to v com bol problem, well, cakal som, ze `UniqueEntity` mi vytvori ingritne obmedzenie, nestalo sa. Tak som aspon cakal, ze to obmedzenie bude na urovni Doctrinu (teda aplikacnej vrstvy ktora uzko spolupracuje s databazou), nestalo sa. `UniqueEntity` totiz obmedzenie vytvori ale validator sa spusti az na urovni formularov (da sa samozrejme manualne zavolat), co som vsak nevedel a teda mi do databazy dovolovalo vlozit nevalidne data. 

Ked som si vsak vytvoril novy, minimalisticky projekt, zistil som, v com bol problem.

Dakujem

**Comment by andrejjursa** [comment]
@ZoltanOnody To znie racionalne, je to predsa len valudator nalepeny na entitu a nie constrain, ten ak chces tam treba vlozit inak. Asi unique index cez tie dve polia to spravi. Mozno by stalo za to taketo unique indexy dat na vsetky pripady tohoto validatora.
