### ISSUE TITLE
Add crud for event

### ISSUE THREAD

**Issue by nitrajka** [TIS2017/Nobelisti#43]
- [x] entita event
- [x] entita eventOrganizers
- [x] entita eventLanguages
- [x] prepojenie entit navzajom vztahmi many-to-one a one-to-many
- [x] list events in table
- [x] vytvorit event_type_languages tabulku
- [x] list event_type_languages in table 
- [x] assign/unassign event_type language
- [x] add event
- [x] edit event (iba update dat) 
- [x] edit event -assign/unassign organizer k eventu (+ autocomplete)
- [x] edit event -assign/unassign language k eventu (+ autocomplete)
- [x] delete event

####Fixes
- [x] Javascript block, jquery
- [x] `autcomplete()`, zavolanie `log()`, dizajn nech je podla navrhu
- [x] assety, inline css, 
Extends #17

**Comment by ZoltanOnody** [comment]
not closed yet

**Comment by Radcho** [comment]
Pridavam languages pre event types

**Comment by nitrajka** [comment]
Ok, ja dokoncujem zobrazovanie languages tabulky pre event

**Comment by Radcho** [comment]
Mam trochu dotazy k modalu. Najhlavnejsi, kliknutie `assign` mi nic nespravilo. Druhy trosku menej podstatny, button je vzdy cerveny, kedze ma v markupe nastaveny danger class, nemalo by to tiez byt nastavitelne?
