### ISSUE TITLE
Update forms according to symfony forms best practices

### ISSUE THREAD

**Issue by andrejjursa** [TIS2017/Nobelisti#57]
https://symfony.com/doc/3.4/best_practices/forms.html
http://symfony.com/doc/3.4/reference/forms/types.html
https://symfony.com/doc/3.4/validation/groups.html

**Comment by ZoltanOnody** [comment]
@viktorria implementuj pls tieto zmeny do komponentov ktore si robila ty, tiez zmen `unique` na `unique_together` ako sme sa o tom rozpravali a predaj validaciu (`@Assert/...`) na jednotlive fieldy v Entite. 

Nechc potom mozme brat tie tvoje komponenty ako ukazkove a ostatne robit podla toho, oki?

**Comment by viktorria** [comment]
oki :)
