### ISSUE TITLE
pridat katalog poziadaviek

### ISSUE THREAD

**Issue by ZoltanOnody** [TIS2017/Nobelisti#6]
Na https://docs.google.com/document/d/16NUc9-gFQM_FESoHAW3LiRYtpkOmsd4-vdN2x8B9esI/edit# je predbezny zoznam poziadaviek, po schvaleni zadavatelom, by trebalo ho ulozit (ako docs + ako pdf) a uploadnut do `/docs/katalog_poziadaviek.pdf`.

**Comment by pavelpetrovic** [comment]
zadavatelovi davate skontrolovat len 1) zapis zo stretnutia a 2) hotovy katalog poziadaviek, ale az potom, co cviciaci povie, ze uz je pripravene na kontrolu zadavatelom. cviciaceho treba jednoznacne upozornit, ze ste hotovi a chcete, aby to skontroloval.  dakujem.

**Comment by Radcho** [comment]
Treba pockat na schvalenie cviciacim pred spravenim pull requestu

**Comment by andrejjursa** [comment]
Cize prisiel mi email o prvotnej verzii katalogu na google docs. Vsetci (@TIS2017/aaaa) si prosim precitajte tieto poznamky:

1. titulna strana, chce to nejaku upravu, nazov projektu a dokumentu na stred, na spod moze byt meno teamu ale chcem, aby na kazdom dokumente boli vase mena,
2. obsah prosim nech ma nadpis Obsah, cislo strany je I. (rimska 1) nie arabska, strana z uvodom je strana, kde sa zacina arabske cislovanie,
3. 1.1 Ciel katalogu poziadaviek, obsah toho, co sa text snazi povedat, by som povedal, ze je ok, ale formulacia je priserna, prosim vas prepiste to tak, aby to malo uroven, zaroven vypustite niektore zbytocne informacie (napr. ze dokument ma pisomnu formu), naviac uz tu vas musim opat upozornit na formatovanie textu, poprosim vas, aby ste dokument pisali pismom s patickou, toto je tlacovy dokument, druha vec je formatovanie odsekov, treba nastavit roztiahnutie na celu sirku strany (resp. zarovnanie podla okrajov alebo ako to uz pomenuvaju v tomto editore), a nech je pred a po kazdom odstavci aspon 0.25em miesta aby bolo vidiet, kde zacina novy a konci stary odstavec,
4. 1.2 Rozsah projektu, obsahuje strucny popis, vyborne, problem je jeho forma hovoroveho prejavu, prosim vyvarujte sa nadmernemu pouzivaniu roznych hovorovych spojok ako "ze", "teda", "a tak", "a teda", "a potom" ci dalsich, tu ide o technicky dokument, ktory ma mat spravnu formu, najlepsie je ho pisat pouzitim autorskeho pluralu, posledna veta v tejto sekcii je zbytocna,
5. 1.3 Definicie, akronymy, skratky, prosim pouzivajte slovo pouzivatel a nie uzivatel (to je hovorovy vyraz), v slovencine sa na konci zoznamu pise ciarka a nie bodka (vynimka je posledna polozka zoznamu, tam sa pise bodka), uprava zoznamu je opat problematicka, prosim pouzite pre text nejake odsadenie pre zarovnanie nasledujucich riadkov rovnakeho prvku zoznamu, podciarknutie nazvu zruste, pouzite iny druh zvyraznenia (kurzivu ci hrube pismo), btw. nie o ucastnikov ale o ucastnikoch, skuste sa tiez vyvarovat pouzivaniu lomitka ako nahrady spojky "alebo" a pouzivajte radsej spojku "alebo",
6. 1.4 Referencie, este raz pripominam, ze toto je tlacovy dokument, linky dajte do pouzitej literatury a do tejto casti dajte referencie na literaturu (ano v tomto pripade bude vsetko webovy odkaz, ale je dolezite, aby bol v tlacovom dokumente skutocne odkaz a nie iba klikatelny link, ktory funguje v pdf verzii),
7. 1.5 Prehlad zvysneho dokumentu, toto nie je kniha, nema kapitoly, ma sekcie, za dalsie, ak chcete informovat o com dalsia sekcia je, napiste to priamo do vety, ktora ju popisuje, ak je to vobec nutne a nepiste o nejakej sekcii omacku a potom "Konkretne sa tu docitame to, to a to ...",
8. 2.1 Perspektiva produktu, prosim vas Symfony 3 nie je platforma ale framework, a ked uz pisete verziu k Symfony, tak ju piste aj k Twigu a Doctrine (predpokladam, ze ide o Twig 2 a Doctrine ORM 2),
9. 2.3 Pouzivatelia, pridajte prosim UML Use-Case diagram s referenciou v texte, v ktorom detailnejsie opisete co je na diagrame zobrazene, samozrejme moze ostat odkaz na sekciu, kde su specificke poziadavky popisane,
10. 2.4 Predpoklady a zavislosti, "Aplikacia zavisi od spolahlivosti serverov." preco tam uvadzate taku samozrejmost, ktora plati pre kazdu server-side aplikaciu? Tu ste mali spomenut skor ake platformovo zavisle technologie bude aplikacia vyzadovat k svojmu realizovaniu a behu (napr. php 7.1, docker engine, docker compose, nginx alebo apache server a spolu s nimi symfony, twig, doctrine, mysql, ze sa predpoklada prevadzka na platforme linux, konkretnejsie debianovskej distribucii - velmi pravdepodobne priamo debian - to ste si mali zistit u zadavatela), omacku o tom, ze technologie maju dokumentaciu (ved to maju ostatne vsetky) a vdaka nej ste schopny projekt realizovat si prosim odpustite, to tam nema co hladat,
11. 3 Specialne poziadavky, ani jedna poziadavka nema ciselny kod (cisla sekcie nie su ciselny kod poziadavky), prosim pouzivat ciselne kody napr. vo formate R-## a potom R-##-## pre parcialne delenie poziadavky do mensich casti, pre vsetky (a tym myslim VSETKY) poziadavky plati, ze ak su delitelne na mensie casti, tak musia byt delene na mensie casti, napriklad vsetko co je v sekcii 3.1 my pride ako dve poziadavky smerovane na pouzivatela, ktore sa daju rozdelovat na mensie celky (napr. to o tom formulare), naviac je to neuplne, co sa ma stat, ked pouzivatel odosle formular ale prednaska je uz plna lebo aj niekto iny stihol registraciu vyplnit a obsadil posledne volne miesto? nikde nic, ziadne podrobnosti a use-case, ziadne kauzalne nasledky cinnosti pouzivatelov, popis administracie je uplne o nicom, takto sa poziadavky nezapisuju (ziadne vymenovanie cez zoznam), opat tam v jednej casti vidim (link), treba mat zoznam literatury (lepsie oznacenie je referencie) a tieto referovat v texte, 3.3.1 je co prosim vas? ked uz chcete pisat o databaze, tak jednoznacne napisat ake tabulky a ake udaje maju obsahovat a nie napisat vseobecne "treba vytvorit databazu", cele poziadavky v sekcii 3 prepisat poriadne!

A este jedna vec, ktora plati pre uplne cely dokument a to je chybajuce delenie viet ciarkami, prosim opravit. Hovoril som aj s Tomasom, sam mi povedal, ze dokument nie je zrozumitelny, treba na tom zapracovat.

**Comment by ZoltanOnody** [comment]
- [x] fix 1. @Radcho 
- [x] fix 2. @Radcho 
- [x] fix 3. @Radcho (Format)
- [x] fix 3. @nitrajka (Formulaica)
- [x] fix 4. 
- [x] fix 5. @ZoltanOnody
- [x] fix 6. @Radcho 
- [x] fix 7. @ZoltanOnody
- [x] fix 8. @ZoltanOnody
- [x] fix 9.
- [ ] fix 10. @ZoltanOnody
- [x] fix 11. @viktorria

Poznamky od Tomasa
- [x] zmazat zmienky o "intuitivnom" rozhrani
- [x] lepsie popisat co je personikovany email
- [x] aplikacia ma informovat zadavatela (na email uvedeny pre Event) a nie administratora
- [x] lepsie popisat testovanie templatov
- [x] templaty prepisat na sablony
---

Otazky na teba, @andrejjursa 
- ak tomu spravne rozumiem, mozme kapitolu 1.5 celu zmazat? 
-  k 9. bodu, vedel by si nam prosim ukazat priklad takeho diagramu?


@Saamoot vravis, ze dokument je nezrozumitelny, mohol by si sa prosim vyjadrit konkretnejsie?

**Comment by andrejjursa** [comment]
@ZoltanOnody sekcia 1.5 (sekcia, nie kapitola, toto nie je kniha, kapitoly su v knihe) tam ostat musi, ziadne mazanie
@TIS2017/aaaa k bodu 9. vam dam do pozornosti material z prednasky (http://dai.fmph.uniba.sk/courses/tvorbaIS/sl/use_cases.pdf), ci to uz prednasane bolo, neviem, je to nalinkovane na stranke, ak to minuly tyzden nebolo, urcite to bude zajtra

**Comment by Radcho** [comment]
Bod cislo 2. sa v Google Docs neda spravit.
Iba kebyze manualne piseme na spodok dokumentu strany.

Asi by bolo vhodne pred prerobenim do pdf, toto manualne zmenit.

**Comment by andrejjursa** [comment]
@Radcho ale v ms word ci libre/open office ci v latex to ide, takze moznosti je mnoho ...

**Comment by Radcho** [comment]
@andrejjursa Problem s robenim v office alebo latex, je ten, ze sa nam tazko bude robit naraz a synchronizovat tu dokumentaciu. Takto to mame jednoduche. Cize navrhujem, ze jeden clovek to pred odovzdanim stiahne a upravi v inom rozumnom programe.

**Comment by andrejjursa** [comment]
@Radcho alebo tak 👍

**Comment by nitrajka** [comment]
@andrejjursa 

1. CHCES, alebo je to niekde napisane? Pridas link?

2. vies nam prosim poslat link, kde by sme nasli info o takychto upravach? nech sa s tym nabuduce neobtazujes. [EDIT: aj tie linky co sa tykaju cislovania stran. Dakujem.]

3. "prosim vas prepiste to tak, aby to malo uroven," -> vies nam dat priklad nejakej prisernej vety? a vdaka za taktnost.

"vypustite niektore zbytocne informacie (napr. ze dokument ma pisomnu formu)" -> autor chcel poukazat na vyhody pisomnej formy a nie na to ze "aha, je to na papieri". Takze tuto vetu iba prerobim, aby sa dala pochopit ako ju autor myslel.

7."toto nie je kniha, nema kapitoly, ma sekcie," -> vdaka sa konstruktivnu kritiku! 

"napiste to priamo do vety, ktora ju popisuje" -> nechceme mat predsa dlhe necitatelne vety ;) takze netusim ako si to inak myslel.

10. "si prosim odpustite, to tam nema co hladat," -> pardon, (2.4) z prednasok a materialov nam nebolo uplne jasne, co by mala tato SEKCIA obsahovat.

11. "(cisla sekcie nie su ciselny kod poziadavky)" -> vid [materialy ku katalogu](http://dai.fmph.uniba.sk/courses/tvorbaIS/tis/new.html) Nikde tam nebolo spomenute, ze to tak nemoze byt.
``` Každá požiadavka musí mať svoje označenie (číslo alebo nejaký iný identifikátor), aby sa na ňu dalo odkazovať z ostatných dokumentov``` Ma oznacenie? Ma.  No, vdaka za upozornenie, prerobime to.

" naviac je to neuplne, co sa ma stat, ked pouzivatel odosle formular ale prednaska je uz plna lebo aj niekto iny stihol registraciu vyplnit a obsadil posledne volne miesto? nikde nic, ziadne podrobnosti a use-case, ziadne kauzalne nasledky cinnosti pouzivatelov, popis administracie je uplne o nicom, takto sa poziadavky nezapisuju (ziadne vymenovanie cez zoznam)" -> mas pravdu @Radcho @ZoltanOnody viete to napisat detailnejsie?

Vsetky body, ktore @ZoltanOnody vytvoril teda nechajme. Ja osobne si beriem na starosti
3. -> uprava textu, format textu niekto spravte vy prosim.

Viktorria, prosim ta, sprav toto:
11. -> ciselne kody + rozclenenie poziadaviek na mensie casti 
treba potom popisat tie detaily, co boli spomenute vyssie k tym poziadavkam.

**Comment by andrejjursa** [comment]
@nitrajka k tvojim pripomienkam:

* k 1. preco ten caps-lock, hneva ta snad, ze sa snazim aby vystup vasej prace bol na urovni studentov bakalarskeho studia? ano, chcem aby dokument mal racionalnu titulnu stranku, ako na bakalarsku pracu, nazov projektu a pod nim napisany nazov dokumentu (teda katalog poziadaviek) pekne v strede, neziadam aby ste tam uvadzali nazov fakulty, chcem len toto + aby na dokumente boli vsetky mena autorov,

* k 2. myslim, ze finalnu upravu cislovania uz vymyslel @Radcho ,

* k 3. toto je momentalny text (predpokladam, ze uz je zmeneny od verzie, ktoru som povodne komentoval, btw. dalsiu budem hodnotit, az mi date vediet, ze je na to pripravena): "Cieľom katalógu požiadaviek je stanoviť si očakávania od projektu vo forme požiadaviek.  Keďže tieto požiadavky sú stanovené písomne, zadávateľ si vytvára presnú predstavu o službách a funkciách aké má výsledný produkt poskytovať. Vďaka tomu nevzniká toľko nedorozumení medzi zadávateľom a poskytovateľom a pokrok vo vývoji je merateľný. A teda sa dá povedať, v akej fáze vývoja produktu sa poskytovateľ nachádza. 
Katalóg požiadaviek je záväzný pre obe strany. Vďaka tomu zadávateľ nemôže svoje požiadavky po schválení katalógu oboma stranami meniť.", teraz to skusim ja napisat trochu formalnejsie: "Predmetom tohoto dokumentu je určiť a špecifikovať požiadavky na softwarové dielo. Obsah dokumentu vznikol po dohode so zadávateľom softwarového projektu a ako taký je záväzný pre obe zainteresované strany. Špecifikované požiadavky budú počas vývoja ako aj po ukončení vývoja softwarového produktu slúžiť na vyhodnocovanie správnosti softwaru zadávateľom aj realizátorom." prosim porovnaj si formalnu a obsahovu stranku oboch textov a posud sama aky je medzi nimi rozdiel,

* k 7. ano vety cheme pokial mozno kratke, no pokial je nutne spomenut viac informacii, tak nech je vsetko zhrnute v jednom co mozno najkratsom suveti, ktore popisuje odkaz na danu sekciu dokumentu,

* k 10. prosim ak to ani z toho co som napisal v prvej vlne komentarov nie je zrejme a stale mas konkretne pochybnosti, skus formulovat otazku jasnejsie aby som ju vedel pochopit a zodpovedat, v skratke by mala tato sekcia dokumentu pojednavat o tom, na akej platforme bude softwarove dielo nasadene, od akych softwarovych kniznic napr. bude zavisle, prip. od akych inych aplikacnych technologii je zavisle (napr. databaza MySQL) a pod.,

* k 11. je mozne, ze Petrovic formalnu stranku dokumentu katalogu poziadaviek prednasa nie uplne do hlbky, nicmenej v realnej praxi sa poziadavky oznacuju alfanumerickymi kodmi, zapisuju sa v tabulkach aj s use-case, s tym, ktory pouzivatelia s danou funkciou aplikacie prichadzaju do styku, s tym ako tato poziadavka ovplyvnuje spravanie dalsich funkcii a pod., toto ani ja a ani Petrovic nechceme, jedine co chcem je, aby poziadavky neboli sekcie v dokumente a boli oznacene rozumne alfanumericky, granularne delene a vycerpavajuco vypisane, jedine tak sa da potom ucinne merat miera splnenia zadania a dosiahnuta kvalita produktu.

Ak budes mat dalsie otazky, nevahaj hned napisat, pokusim sa odpisat cim skor.

**Comment by nitrajka** [comment]
@andrejjursa Prosim ta, posli mi nejaky link/zoznam podla ktoreho mozme v buducnosti formatovat dokumenty. Teda v pripade ak vyzadujete taketo velmi detailne upravy a mate to niekde spisane (napr. rimske cislice).

Vdaka za tu 3. Vyzera to formalnejsie.

**Comment by andrejjursa** [comment]
@nitrajka nemam ziaden taky link ci zoznam, jedine dve veci som chcel, a to aby titulna stranka mala nazov dokumentu na stred, boli tam mena vas vsetkych realizatorov projektu a aby sa cislovanie obsahu arabskymi cislicami zacalo az na stranke, kde je zacina uvod dokumentu, ostatne strany (v nasom pripade iba obsah, ine strany tam nemame), by mali mat rimske cisla, alebo mozno ani nemusia mat ziadne cislovanie (vacsinou to bude obsah - table of contents - na jednu stranu), je na tomto bode nieco nezrozumitelne? ostatne uvidis, ze az budes pisat bakalarsku pracu - tiez technicky/vedecky dokument - tiez sa to od teba bude vyzadovat, prave takato uprava, dokonca este viac

**Comment by Saamoot** [comment]
@ZoltanOnody + @TIS2017/aaaa nezrozumitelne v zmysle, ze po precitani odsekov, ktore popisovali funkcionalitu alebo sposob implementacie, som mal problem porozumiet co ma funckionalita poskytovat alebo ako bude nieco naimplementovane (odseky co boli formalneho typu som neriesil) a to cca viem o com applikacia ma byt, na druhu stranu mozno to sposobuje, ze som neporozumel kedze sa popis nezhoduje s mojimi predstavami.

Pred tym nez som toto pisal som si to znova precital a bud pomohlo, ze som to znova cital alebo ste to rozsiahlo prekopali. Ostali nejake veci, ktore mi pridu stale nejasne, nezrozumitelne a ze sme sa nepochopili, su to nasledovne veci:

Nejasne veci:
----
- **intuitivne a jednoducho preklika**
  - `ake je to intuitivne preklikavanie ?` - to je to pravidlo, ze na webovej stranke sa ma dat zo vsade dostat na dalsie hoci ake miesto do 2 max 3 kliknuti ? Alebo je to rozlozlenie stranky v troch stlpcoch, ktore maju sucet sirky 1024px ?
  - `ake je jednoduche prekliklavanie ? resp opak ake je zlozite preklikavanie ?` - odkazy budu kriklavej farby ? alebo budu blikat ?
- **intuitívne sa pohybovať po stránke**
  - `ake je intuitivne pohybovanie sa vo virtualnom priestore ?` - ukazovatel mysky bude "snapovat" na linky a iny pouzitelny obsah ? alebo sa bude navigovat po stranke pouzitim klavesnice ?
- **personifikovaného e-mailu**
  - zosobnovat emaily nemame v plane ... ale nie, mysleli ste email-u zo zvolenou sablonou ?

Veci na ktorych sme sa nepochopili:
----
- **Aplikácia tiež informuje administrátora** - v sekcii (aby sme potesili andreja, vtip samozrejme ) dokumentu 3.2, applikacia nema informovat administratora ale zadavatela udalosti, zadavatel udalosti nema mat pristup do applikacie, takze pre udalost treba pole pre email kam ma email s informaciou obsadenosti ist. Zadavatela udalosti vobec nemusite riesit. Dufam, ze sme Vam medzi casom nepovedali inak, v tom pripade tento bod ignorujte.
- **Testovanie funkčnosti templateov** - sekcia 4.2.5 tato funkcionalita sa dako vymkla z pod kontroly od nasho stretnutia, povodna idea bola spravit `nahlad` sablon, napriklad by bola stranka, kde by bol zoznam sablon, nazvy by boli klikatelne(link, button, ...) a po kliknuti by sa napr v `bootstrap-modal` "okne" nacitala sablona. Avsak poslat email s vybranou sablonou znie velmi rozumne, tak mozno pod nahlad v okne dat input na email a tlacitko na poslanie ?(ak moc vymyslam staci ten nahlad)

----
Co sa tyka nejasnych veci tam som prehanal ale to preto aby som dal najavo, ze pekne slova su na nic, ked sa daju chapat viacerimi sposobmi, toto nie je dokument pomocou, ktoreho sa snazite nieco predat ale ma obsahovat veci co sa maju spravit. To iste aj pre `template` mate to napisane co to znamena/je ale odporucam pouzivat slovo `sablona` nevzniknu potom zvierata ako `Templatey` ;) (dufam, ze to nie je spravne poslovencenie @_@)

**Comment by ZoltanOnody** [comment]
@Saamoot dakujem za objasnenie

> Pred tym nez som toto pisal som si to znova precital a bud pomohlo, ze som to znova cital alebo ste to rozsiahlo prekopali. 

Medzicasom sme na tom popracovali. Obsah je sice rovnaky, ale forma pisania je formalnejsia a menej "hovorova". Tak mozno pomohlo oboje.


Nejasne veci:
----
> **intuitivne a jednoducho preklika**
>  - `ake je to intuitivne preklikavanie ?` - to je to pravidlo, ze na webovej stranke sa ma dat zo vsade dostat na dalsie hoci ake miesto do 2 max 3 kliknuti ? Alebo je to rozlozlenie stranky v troch stlpcoch, ktore maju sucet sirky 1024px ?
>  - `ake je jednoduche prekliklavanie ? resp opak ake je zlozite preklikavanie ?` - odkazy budu kriklavej farby ? alebo budu blikat ?

Ja osobne si myslim, ze cele to "intuitivne preklikavanie" je tak trochu zvast a je normalne, ze to bude user friendly. Vsak v konecnom dosledku to ma byt 1 page, kde bude link na formular a zmenu jazyka. (tak ako na tom webe co ste nam v piatok ukazovali.) Nehovoriac o tom, ze to rozhranie sa bude riesit cez templaty a teda to nebude starost aplikacie ako takej.


> - **intuitívne sa pohybovať po stránke**
>  - `ake je intuitivne pohybovanie sa vo virtualnom priestore ?` - ukazovatel mysky bude "snapovat" na linky a iny pouzitelny obsah ? alebo sa bude navigovat po stranke pouzitim klavesnice ?

Navrhujem najst vsetky vyskyty "intuitivne" v tom texte a preformulovat tie vety, pretoze ani mne nieje tak celkom jasne ako to moji kolegovia mysleli. 

> - **personifikovaného e-mailu**
>  - zosobnovat emaily nemame v plane ... ale nie, mysleli ste email-u zo zvolenou sablonou ?

Email so zvolenou sablonou nieje problem zosobnovat a bude to +- fungovat out of the box, samozrejme tuto funkcionalitu pouzit nemusite no podla mna je to nice to have. V podstate ide o to, ze v tej sablone (napriklad v emaily ktory sa posle po registracii) budete mat nieco ako:

``` 
Ahoj {{registration.first_name}},
zaregistroval si sa na Event, tvoje registracne cislo je {{registraion.number}}.
```

Kde sa `{{registration.first_name}}` nahradi menom prihlaseneho. Toto naprogramovane bude, kedze tam treba pridat `{{registration.number}}`. To ci to vyuzijete aj na oslovenie, alebo oslovenie nechate genericke, je na vas. Dufam, ze je to z tohto popisu jasne.


Veci na ktorych sme sa nepochopili:
----

> - **Aplikácia tiež informuje administrátora** - v sekcii (aby sme potesili andreja, vtip samozrejme ) dokumentu 3.2, applikacia nema informovat administratora ale zadavatela udalosti, zadavatel udalosti nema mat pristup do applikacie, takze pre udalost treba pole pre email kam ma email s informaciou obsadenosti ist. Zadavatela udalosti vobec nemusite riesit. Dufam, ze sme Vam medzi casom nepovedali inak, v tom pripade tento bod ignorujte.

Ano tu sme sa nepochopili. V poriadku, nebude problem pridat pre event do databazy field `organizer_emails` kde bude zoznam emailov na ktore sa tieto statistiky budu posielat. Dakujeme za ozrejmenie.

> - **Testovanie funkčnosti templateov** - sekcia 4.2.5 tato funkcionalita sa dako vymkla z pod kontroly od nasho stretnutia, povodna idea bola spravit `nahlad` sablon, napriklad by bola stranka, kde by bol zoznam sablon, nazvy by boli klikatelne(link, button, ...) a po kliknuti by sa napr v `bootstrap-modal` "okne" nacitala sablona. Avsak poslat email s vybranou sablonou znie velmi rozumne, tak mozno pod nahlad v okne dat input na email a tlacitko na poslanie ?(ak moc vymyslam staci ten nahlad)

Mne osobne sa paci myslienka poslatia toho emailu. Kludne tam moze byt ten input field tak ako pises. Toto este v tom dokumente ozrejmim.

----
> Co sa tyka nejasnych veci tam som prehanal ale to preto aby som dal najavo, ze pekne slova su na nic, ked sa daju chapat viacerimi sposobmi, toto nie je dokument pomocou, ktoreho sa snazite nieco predat ale ma obsahovat veci co sa maju spravit. To iste aj pre `template` mate to napisane co to znamena/je ale odporucam pouzivat slovo `sablona` nevzniknu potom zvierata ako `Templatey` ;) (dufam, ze to nie je spravne poslovencenie @_@)

"Sablona",... toto slovo mi seriozne nenapadlo. Ano, pouzitie slova sablona bude asi (kvoli sklonovaniu) vhodnejsie. 

Vdaka za feedback

**Comment by Saamoot** [comment]
@ZoltanOnody 

Nejasne veci:
----
- **intuitivne a jednoducho preklika** - zvasty prec, zbytocne zvadzaju na zle chodnicky ale je to tak ako si napisal, ze sablony pre registracny formular aj pre email-y nieriesite, to budeme generovat u nas.

- **intuitívne sa pohybovať po stránke** - *thumbUp*

- **personifikovaného e-mailu** - aaah toto urcite chceme, dakujem za objasnenie, chapanie islo asi na vylet, ked som to cital, nepriznam sa ako som to pochopil ...

Ohladom **veci na ktorych sme sa nepochopili**, slova su zle taky navrh databazy by vsetko povedal jednoznacne(urcite nie ale ... :) ) A dakujem za prisposobania, ja som spokojny, ze nieco co sa zide bude implementovane aj ked to nie je v prvom zadani.

**Comment by ZoltanOnody** [comment]
Navrch databazy isto bude, no osobne by som to nerad pchal do katalogu poziadaviek, kedze to nieje poziadavka ako taka. V technickej dokumentacii, kde bude implementacia projektu, samozrejme bude. Budem rad, ked sa nam k tomu navrchu potom vyjadris. :)

**Comment by ZoltanOnody** [comment]
@Saamoot prosim ta, vedel by si nam poslat zoznam zavislosti na projekt? myslim, aky linux bezi na tych serveroch, ci tam je docker,... proste nejaky popis servera na ktorom to ma bezat. :-)

**Comment by Saamoot** [comment]
@TIS2017/aaaa 
Na servery, ktory pouzivame pouzity operacny system `debian` `verzie 8 (jessie)` .

`Docker` momentalne `nepouzivame`, takze ho nemame ale je mozne ho doinstalovat. 

`PHP` verzia v pripade, ze sa nepouzije docker by mala ostat aktualna a to je `5.6`. 

`Databazu` pouzivame `mariaDB` verzie `15.1` distribucia `10.0.30`.

Ako `webovy server` pouzivame `apache2` verzie `2.4`, radi by sme pri nom aj ostali.

To su verzie, ktore momentalne pouzivame na servery, kde je stara app a mala by na nom bezat aj nova verzia applikacie.

V pripade dockeru by som pouzil najnovsiu verziu `php` a `apache`-a. Ci robit novu instaciu db v kontajnery je na zvazenie.

Ak sa rozhodnete ako riesenie nam dat produkt zabaleny v docker kontajnery prosim o guide ako nasmerovat komunikaciu na vas kontajner, s tym, ze nesmie prebrat vsetku komunikaciu na standarnych portoch `80`, `443` a `3306`

**Comment by ZoltanOnody** [comment]
@andrejjursa @Saamoot vsetky poziadavky boli zapracovane (okrem predpokladov a zavyslosti, tie spiseme vecer). Ak si najdete cas, mohli by ste sa nam na to este raz pozriet? Dakujeme!

**Comment by andrejjursa** [comment]
@Saamoot doporucujem zakontainerovat aj databazu, kvoli konzistencii, predsalen tam moze byt rozdiel vo verzii MySQL jazyka, hoci Doctrine by to mal kompenzovat, lepsie je v produkcii pouzivat tu verziu, na pre ktoru sa vyvyjalo

@ZoltanOnody pozriem na to hned ako budem moct

**Comment by andrejjursa** [comment]
@TIS2017/aaaa priamo do dokumentu som popisal komentare a navrhy na zmeny v texte tak, aby bol text viac formalny a neobsahoval zbytocnosti, prosim pozrite si to v google docs a zapracujte pripomienky

**Comment by Saamoot** [comment]
@TIS2017/aaaa zdravim rozpraval som sa s @andrejjursa a narazili sme na nezhodu co sa tyka pouzivatelskych(administratori) uctov. Vacsinou si kazda applikacia eviduje pouzivatelov s pristupom sama. Implementacia zoznamu pouzivatelov sa robi cez databazu. Takze Vas ziadame o rovnaky sposob implementacie aj v pripade tejto aplikacie. 

Priklad tabulky v tabaze:
- id
- login
- salt
- encrypted_password
- deleted // soft-delete

A napriklad metoda `crypt`. Samozrejme mozete pouzit lubovolnu alternativu, ktora robi nieco podobne.

**Comment by ZoltanOnody** [comment]
Katalog by uz mohol byt vo finalnom stave.

V dokumente boli spomenute nice to have poziadavky:
- online editor templatov
- hromadne rozosielanie personifikovaych emailov (napr. o zmenach udalosti) priamo cez administraciu

Tieto poziadavky sa budu programovat za predpokladu, ze na ne ostane cas. A teda niesu nutne pre odovzdanie hotoveho projektu a nemaju ovplyvnit jeho hodnotenie.

@Radcho mohol by si prosim pozriet na zmeny ktore som navrhol, popripade ich upravit a approvnut?

**Comment by andrejjursa** [comment]
@TIS2017/aaaa pozrel som dokument v sucasnom stave a doplnil som don nejake komentare a navrhy. Uz sa to zda sa blizi finalnemu dokumentu ale este tam treba par uprav (nehovoriac o tom, ze este niektore starsie navrhy a poznamky nie su zapracovane).

**Comment by andrejjursa** [comment]
@TIS2017/aaaa dostal som info od Peti Kopacovej, ze z ich strany je katalog ok, takze ho prosim dajte v pdfku na do repozitara a toto mozete potom zavriet (pozn. originalny dokument na googledoc nechajte, na zaver sa pise tzv. zaverecna sprava a ta spaja vsetky dokumenty).

**Comment by ZoltanOnody** [comment]
spravim to.
