### ISSUE TITLE
Vytvorit specifikaciu pre templaty

### ISSUE THREAD

**Issue by ZoltanOnody** [TIS2017/Nobelisti#7]
- treba vymysliet a spisat aka bude presna struktura templatov.
- vytvorit ukazkovy template

**Comment by ZoltanOnody** [comment]
Rozmyslam nad e-mailovymi templatmi....

# Problem
Povodna idea bola aby v templatoch bol subor `registration.<lang>.twig` ktory by mal napr obsah.
```
Hi {{first_name}},
your registration number is {{registration_number}}.
```

Na konci posledneho stretnutia sa vsak spomenulo, ze takto nebude mozne upravit predmet emailu.

# Riesenie 1
Mohli by sme mat subor `registration.<lang>.json.twig` ktroy by mal obsah
```javascript
{
  "subject": "Event registration",
  "sender": "my@email.com", // ak by to nahodou bolo treba
  "content": "Hi {{first_name}},\nyour registration number is {{registratino_number}}."
}
```
JSON vsak nepodporuje multiline stringy a trebalo by teda parsovat newline na `\n`. Toto sa mne osobne moc nepaci.

# Riesenie 2
Mohli by sme mat 2 subory.

 `registration.<lang>.json.twig` ktory bude obsahovat meta data.
```javascript
{
  "subject": "Event registration",
  "sender": "my@email.com" // ak by to nahodou bolo treba
}
```

`registration.<lang>.content.json.twig` ktory by obsahoval samotny obsah emailu.
```
Hi {{first_name}},
your registration number is {{registration_number}}.
```

Toto riesenie sa mne paci viacej lebo netreba template upravovat a je to podla mna cistejsi sposob.

---
Co si o tom myslite @Saamoot, @andrejjursa, @TIS2017/aaaa ?

**Comment by andrejjursa** [comment]
@TIS2017/aaaa Zdravim,

bohuzial odpisujem trochu neskor, zda sa, ze ani @Saamoot nemal cas. S Tomasom sme toto riesili este v piatok a ak sa dobre pamatam, tak predstava bola asi takato:

Nech existuje sablona pre nejaky email, povedzme, ze ju nazveme `email.registration.twig` ktora obsahuje:

```twig
{{salutation|format(first_name)}}

{{text|format(registration_number)}}

{{regards|format(sender)}}
```

a potom k nej by mali byt jazykove subory json alebo yaml, napr. `email.registration.sk.yaml`:

```yaml
subject: Registrácia na prednášku doc. Janka Hraška o využití solárnej energie
salutation: Dobrý deň %s
text: |-
  ďakujeme, že ste sa zaregistrovali na prednášku doc. Janka Hraška o využití solárnej energie.
  Vaša registračné číslo je %s.
  Prednáška sa bude konať dňa 25.11.2017 o 14:30 sále 12 na
  Prednáškovej ulici č. 2
  123 45 Prednáškovo
regards: |-
  S pozdavom,
  %s
```

Pozn. vysvetlenie syntaxe viacriadkovych zapisov v [yaml](http://yaml-multiline.info/) (pozn. 2 :), v JSON toto nespravite tak pekne, netvrdim, ze nezapisete viacriadkovy text ale bude to hrozne necitatelne).

Teda nacita sa podla jazyka subor yaml, symfony yaml parser vam da klasicke pole, ktore mozno dat do twig parseru aj spolu s dalsimi informaciamia, ktore prichadzaju z databazy, tj. napr. datum konania ak by bolo treba zobrazit. Potom jednoducho preparsujete twigom sablonu s tymito datami a date do tela emailu.

Ale je fakt, ze som to uz mozno sam trochu poplietol, odkedy sme to riesili s Tomasom prebehlo 10 dni, bolo by super, @Saamoot, keby si to co som napisal potvrdil, zamietol, alebo korigoval.

Pozn. pre vsetkych, ja viem, ze nejak vsetci mate radi ten JSON ale to je jazyk na vymenu informacii. Skutocne lepsie je pouzivat jazyk yaml, ktory je urceny na zapisovanie konfiguracie, da sa v podstate lahko kombinovat aj s markdown syntaxou, co znamena, ze je mozne velmy jednoducho nieco v tele emailu zvyraznit a v popise to nemusi obsahovat rusivy html markup (to si ale vyzaduje dodatocne spracovanie markdown parserom) - keby sa to chcelo namontovat do JSON formatu, bolo by to naprosto neprakticke.

**Comment by Saamoot** [comment]
@TIS2017/aaaa @andrejjursa 
Ohladom formatu `"datovych"` suborov vyberam `yaml` ak ale presvedcite andreja na `json` nemam s tym problem.

Co sa tyka formatu ako sa bude pisat template(sablona), bolo by vhodne aby nebolo staticky definovane, co sa da pouzit. Ale vsetky polozky co sa zadefinuju v datovom subore budu k dispozicii v template.

Samozrejme musia byt k dispozicii aj data z databazy. (Informacie o evente)

Jednoduchy priklad co by mohlo byt akceptovatelne. Data zo suboru by boli schovane pod objektom/polom `data` a informacie z databazy by boli pristupne pod objektom/polom `event`


data zo suboru, priklad:
```
{{data.content}}
```

data zo systemu/databazy, priklad:
```
{{event.title}}
```

aplikovane na priklad od andreja

```
{{data.text|format(registration_number)}}
```

To je momentalna predstava, prosim vyjadrite sa.

**Comment by ZoltanOnody** [comment]
> Ohladom formatu "datovych" suborov vyberam yaml ak ale presvedcite andreja na json nemam s tym problem.

YAML it is.

> Co sa tyka formatu ako sa bude pisat template(sablona), bolo by vhodne aby nebolo staticky definovane, co sa da pouzit. Ale vsetky polozky co sa zadefinuju v datovom subore budu k dispozicii v template.

Vsetky data z datoveho suboru + vhodne udaje z databazy tam pouzitelne budu. (vhodne = na homepage event, pri odosielani emailu - registration (cez ktory sa da pristupit aj k eventu,...)).

> {{data.text|format(registration_number)}}

Neviem co presne robi ten `format` ale verim tomu ze to assighne do premennej :-D 

Suhlasim so vsetkym.

**Comment by andrejjursa** [comment]
@ZoltanOnody modifikator `format` v twigu vlastne robi to iste co napr. v c robi printf, s tym, ze string, na ktory sa modifikacia aplikuje je samozrejme to co sa nachadza pred `|`, struktura by mala byt rovnaka, malo by tam tiez fungovat oznacovanie pozicii cislom vzhladom na poziciu parametra, keby to bolo treba, v podstate to nahradza teda to co dokaze robit php funkcia [sprintf](http://php.net/manual/en/function.sprintf.php).

**Comment by ZoltanOnody** [comment]
toto sa uz dokoncilo a odsuhlasilo, je to spisane v navrhu.
