### ISSUE TITLE
attendee & registration entities

### ISSUE THREAD

**Issue by ZoltanOnody** [TIS2017/Nobelisti#77]

**Comment by Radcho** [comment]
Create registration entity and register atendee at https://github.com/TIS2017/Nobelisti/blob/07f0ff9b3137cccd2a03747d2ccdbb7b965e2c8b/src/src/AppBundle/Controller/DefaultController.php#L59

**Comment by ZoltanOnody** [comment]
@Radcho toto robi podla mna @viktorria . Prosim spytaj sa jej ako je na tom nech nerobite obaja to iste. @viktorria  ty si zas prosim assigni veci na ktorych robis.

**Comment by Radcho** [comment]
Hej robi, len tu nebola tak som si to vzal

**Comment by ZoltanOnody** [comment]
@viktorria ono by to malo fungovat na realnom projekte tak, ze najprv sa nieco mergne a potom sa issue zavrie. este idealnejsie, ze do komentara k PR napises "closes #77" a automaticky to zavrie tuto issue ked sa ten PR mergne. Zatvarat issue pred tym ako je nieco mergnute by sa nemalo.
