### ISSUE TITLE
Vytvorit prazdne admin rozhranie

### ISSUE THREAD

**Issue by ZoltanOnody** [TIS2017/Nobelisti#8]
Treba vytvorit `/admin/` rozhranie kde bude potrebne sa autentifikovat pre pristup

Mozme:
a) to cele nakodit od nuly a spravit minimalisticke rozhranie  - https://symfony.com/doc/current/security/form_login_setup.html
b) pouzit nejaky Bundle, napriklad. https://symfony.com/doc/master/bundles/SonataAdminBundle/index.html

Ja osobne preferujem moznost A. Prosim vyjadrite sa.

**Comment by Radcho** [comment]
Pri puziti postupu A, je na symofny popisany security guide na https://symfony.com/doc/current/security.html
Ja osobne som za tu moznost, mohli by sme pouzit tie roly co su tam spominane.

**Comment by ZoltanOnody** [comment]
toto je uz davno done. #20 #37,..
