### ISSUE TITLE
Template testing - Web

### ISSUE THREAD

**Issue by Radcho** [TIS2017/Nobelisti#84]
Treba pridat testovacie linky do events

## Web testing
- [x] zisti ci kazdy jazyk z events sa nachadza v subore templates

- [x] vacsi test (vyrenderuje linky):
    - [x] /test/event_slug?state=registration_not_started&lang=sk_SK
    - [x] /test/event_slug?state=registration_open&lang=sk_SK
    - [x] /test/event_slug?state=registration_finished&lang=sk_SK
    - [x] /test/event_slug?state=registration_no_capacity&lang=sk_SK
Extends #17

**Comment by Radcho** [comment]
K tomuto drobna otazka, ten state chceme ako ohandlovat? V databaze to nie je, takze je to nieco co bude treba vydedukovat zo stavu entity, cize to bude treba pridat aj do obycajneho renderovania.
Co mi napadlo, bolo tak isto ako sa do twigu posiela `lang` sa posle aj `state` ktory bude mat jednu z tychto hodnot.

**Comment by Radcho** [comment]
Narazil som na dost velku stenu co sa tyka slugov. 
Aktualne je to spravene tak, ze **event_type** ma svoj slug.  **event** moze overridovat zakladnu template nastavenu v **event_type**.
Kedze je ale slug rovnaky pre vsetky eventy, to znamena, ze registracny formular a teda aj testovacie linky su naviazane iba na **event_type**. Nestaci teda aby boli testovacie linky na web iba v **event_type** formulari a nie v **event** formulari?
V **event** formulari by potom stacil len test na jazyky a e-maily.

**Comment by ZoltanOnody** [comment]
Spýtaj sa prosím Tomáša. Už mi nieje úplne jasné ako to bolo myslené.
